version: 0.2
phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - |    
                  if [ ${CODEBUILD_BUILD_SUCCEEDING}=1 ] ; then  

                    aws sns publish --topic-arn arn:aws:sns:us-east-2:806103514809:codedeploy-test --message "Code Build TriggerSNS success value"; 

                  elif [ ${CODEBUILD_BUILD_SUCCEEDING}=0 ] ; then 

                    aws sns publish --topic-arn arn:aws:sns:us-east-2:806103514809:codedeploy-test --message "Code Build TriggerSNS Failed value"; 

                  fi
artifacts:
  files:
    - target/my-web-app.war
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
